### ISSUE TITLE
deploy option generate_types does not seem to work

### ISSUE THREAD

**Issue by damonmaria** [puppetlabs/r10k#1070]
## Describe the Bug
I have the `generate_types` option set: 
```yaml
:cachedir: /opt/puppetlabs/puppet/cache/r10k
:sources:
  ...

:deploy:
  generate_types: true
  purge_levels:
  - deployment
  - environment
  - puppetfile

:git:
  provider: shellgit
```

It appears to run as shown in `access.log`:
```
[2020-05-29 05:51:05] INFO  message: triggered: umask 0022; /opt/puppetlabs/bin/puppet generate types --environme
nt tannery_production --confdir /etc/puppetlabs/puppet --codedir /etc/puppetlabs/code --vardir  /opt/puppetlabs/s
erver/data/puppetserver environment: tannery_production
```

But most often I get errors when deploying that are solved when I manually regenerate types. 

If I manually run the command shown in `access.log` it runs without error. 

## Expected Behavior
Types are regenerated.

## Steps to Reproduce
Not sure what I'm doing differently apart from turning on `generate_types`. 

## Environment
 - Version: 3.5.0
 - Platform: Ubuntu 18.04
 - Setup using puppet-r10k module

## Additional Context
It's also a bit confusing as the FAQ says [regenerating types has to be setup manually](https://github.com/puppetlabs/r10k/blob/master/doc/faq.mkd#how-can-run-i-puppet-generate-types-for-each-changed-environment-during-deployment). But isn't this what the `generate_types` option does?
