### ISSUE TITLE
Allow users to tune behavior on invalid branches

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#117]
When r10k encounters a git branch that contains characters that cannot be in a Puppet environment, it logs a warning and replaces invalid characters with underscores. However this behavior isn't always desired - some users were relying on using invalid branch names to prevent branches from being deployed and thus want to silently ignore them, and others want invalid branch names to be treated as error, have an error logged, and then have that environment ignored.

This behavior should be implemented in `R10k::Source::Git`; this behavior may be restricted to Git sources for the indeterminate future.

Values should be something like the following:

``` yaml

---
sources:
  ops:
    remote: '...'
    branch_settings:
      on_invalid:
      # ignore: Silently ignore invalid branches
      # error: Generate an error and ignore invalid branches
      # correct: Silently correct invalid branches
      # correct_and_warn: Correct invalid branches and generate a warning (default)
```

The restructuring in GH-116 currently removes normalization entirely, so this needs to be implemented before GH-116 can be merged and released.
