### ISSUE TITLE
Support for calling an arbitrary script after deployment

### ISSUE THREAD

**Issue by skottler** [puppetlabs/r10k#121]
It'd be really useful to be able to call an arbitrary script after deployment with a payload about the deployment as an argument. This would be particularly great for doing stuff like triggering an environment/module import in Foreman using the API.

Thoughts?

**Comment by adrienthebo** [comment]
Sounds good to me. I can see one complication though - deployments themselves don't have a single root; they are just a collection of different sources that can be located in arbitrary locations. For example:

``` yaml
---
sources:
  common:
    remote: '...'
    basedir: '/etc/puppet/environments'
  app:
    remote: '...'
    basedir: '/opt/modules/app-deployment'
```

There's not a common location to pass to the post-deployment command. The base directory for each source could be passed to the command as arguments; would that meet your needs? I would like to have a better idea of what you're trying to achieve; could you run me through what kind of work you would expect to do in the command?

Regarding the command invocation, should the exit code of the post-deployment command have any meaning or should it be ignored entirely?

**Comment by skottler** [comment]
Even just knowing when _any_ environment has changed would be useful for what I'm thinking right now. That being said, I think there are a few things that would be great to include just for future-proofing/preventing more work on the same thing going forward:
- list of changed environments (this is most important)
- sources (potentially mapped by environment) if possible

I think that's it, but even knowing that things have changed in an environment is the most important so an import can accurately be triggered.

Thanks for the quick reply!

**Comment by adrienthebo** [comment]
Implementing GH-67 will allow for very fine grained reporting of what changed, so when that's available you'll be able to drill down to see what environments and modules changed, and the versions before and after the update. That's a bit more involved than just running a command and will be a respectable amount of work so I don't see that happening in the near future. However will running a specified command with a list of sources be sufficient for the interim?

**Comment by rnelson0** [comment]
Phil Zimmerman offers a way to do this with his workflow: http://philzim.com/2014/05/02/an-automated-r10k-workflow-that-works/ Ctrl-f for "cap up" or "cap dep" and either replace with your commands and use capistrano to fire off your programs.

In this case, the git repository post-receive hook is providing the information, not r10k, which is cleaner for github users but not as clean for svn users (or git users not using github). However, it might be a better (or at least quicker) roadmap for providing delta information.

**Comment by skottler** [comment]
It's good that there's a workable solution out there, but it's not really ideal for lots of reasons. Since this feature is pretty simple I don't see any reason it shouldn't be part of r10k itself.

**Comment by jhoblitt** [comment]
Much like @skottler, I need to import new classes + envs into foreman after a deployment.  While I imagine there are use cases for a pre/post hook per envs, I think it would be reasonable to start with hooks around the entire deployment run and then worry about per env entry points (side note: it would be nice for the paths to be dynamic so the scripts themselves could live in the repo with the Puppetfile).

Maybe something like?

```
:cachedir: /var/cache/r10k
:sources:
  puppet:
    basedir: /etc/puppet/environments
    prefix: false
    remote: https://github.com/glarizza/puppet_repository.git
predeploy: /etc/r10k/r10kpre.sh
postdeploy: /etc/r10k/r10kpost.sh
:purgedirs:
  - /etc/puppet/environments
```

I think (?) it would be reasonably straight forward to add a new "system" task type and inject them around the the module deployment tasks some wherehere around here: https://github.com/adrienthebo/r10k/blob/master/lib/r10k/cli/deploy.rb#L99

**Comment by jhoblitt** [comment]
Or how about 

```
:sources:
  puppet:
    basedir: /etc/puppet/environments
    prefix: false
    remote: https://github.com/glarizza/puppet_repository.git
    predeploy: /etc/r10k/r10kpre.sh
    postdeploy: /etc/r10k/r10kpost.sh
```

And passing the `basedir` as an argument to the script(s)?
