### ISSUE TITLE
Override purgedirs?

### ISSUE THREAD

**Issue by jbartko** [puppetlabs/r10k#39]
I am using r10k in combination with a gitflow-enabled repository. I would like to maintain the 'master' branch naming convention for the purpose of distributing production-ready code while sidestepping Puppet's lack of support for environments named 'master.'

This may be a hackish workaround, but having a symlink at `/etc/puppet/environments/production` that points to `/etc/puppet/environments/master` yields the behavior I want. My problem is that whenever `r10k deploy environment` is called, r10k deletes the symlink even if the purgedirs directive is commented out or not present (see [this gist](https://gist.github.com/jbartko/5694921) for an example).

I propose that the ability to:
- cleanly disable purgedirs behavior via multiple interfaces (persistently via a configuration file, temporarily via command line), and
- 'whitelist' files from being purged from the basedir (.r10kignore?)

are desirable features.

**Comment by adrienthebo** [comment]
If you could disable purging on a per-source base, would that work?

``` yaml
sources:
  my_env:
    remote: 'git@github.com:my-org/org-shared-modules'
    basedir: '/etc/puppet/environments'
    purge: false
```

Alternately, have you considered changing the default branch from master to production? That way you won't have to fight to make Git and Puppet to align.
