### ISSUE TITLE
"r10k deploy display -p" doesn't reflect the actual status of the environments

### ISSUE THREAD

**Issue by Ancillas** [puppetlabs/r10k#40]
Using `r10k deploy display -p` doesn't accurately reflect the version of the installed modules across Puppet environments.

For Puppetfile entries that specify branches, the module versions are displayed as the branch itself e.g. (master) or (development).  While this indicates what the state will be after the next environment sync, it doesn't indicate the last version that was installed.

For example, if I have 3 months worth of commits in my master branch, but haven't deployed them, then seeing (master) in the output of `r10k deploy display -p` will be misleading.

Either the module version, or the git commit SHA (preferably module version) should be captured, cached, and then displayed when viewing the status of the environments.  I propose a new output scheme, and a slightly different command.  I don't like having the 'display' command as a sub-command of 'deploy', but I'll follow the scheme as I'm guessing it's attempting to follow the [noun] [verb] approach.

`r10k deploy status -p` and `r10k deploy status -p -y` (the latter outputs yaml)

Displays current environments, current module versions, and candidate version to be installed on current branch.  Allow for readable output, and yaml output.

_example yaml template_

```
[environment]:
  sha: [environment-sha]
  modules:
    - [module]
      version: [current-version] 
      branch: [branch]
      candidate_version: [candidate-version]
    - [module]
      version: [current-version]
      branch: [branch]
      candidate_version: [candidate-version]
[environment]
  sha: [environment-sha]
  modules:
    - [module]
      version: [current-version]
      branch: [branch]
      candidate_version: [candidate-version]      
```

_example yaml output_

```
development:
  sha: abc123
  modules:
    - ntp:
        version: 1.1-dev-4
        branch: development
        candidate_version: 1.1-dev-4
    - apt:
        version: 1.1-dev-1
        branch: development
        candidate_version: 1.1-dev-1
production:
  sha: zyx789
  modules:
    - ntp:
        version: 1.0
        branch: master
        candidate_version: 1.1
    - apt:
        version: 1.0
        branch: master
        candidate_version: 1.1
```

When the current version does not match the candidate version, hilight that module in the console output to indicate that it will be upgraded on the next sync.

**Comment by adrienthebo** [comment]
This requests a few features, I'll respond to them in turn.

### Displaying the version of the module on disk as opposed to what's specified in the Puppetfile:

:+1:. I thought that I implemented things to show the currently installed version, but I must have been mistaken about that.

### Displaying the module version/SHA:

This gets a little bit stickier. In theory I could see if any git tags matched the currently checked out branch, but that increases the complexity of this a bit. Cool feature, would be awesome to have, but I don't know how much this should be prioritized. :+1: for the idea though.

### Command layout:

For the sake of sanity, every action needs to be under a subcommand. For instance, the deploy actions that use an `r10k.yaml` are entirely different from the puppetfile actions. They use the same underlying behavior but they aren't necessarily joined. Thus, doing `r10k puppetfile display` is going to be different from `r10k deploy display`. Does that make more sense?

### `r10k deploy status`

:+1: for the subcommand name.

However, everything has to be complicated. :) To correctly show if a module is out of date, you would have to fetch the latest information - and if you're operating on a lot of modules, this could take a while. If nothing else, this should preserve `deploy display` or a similar command so that you can see the status of things without doing a fetch.

Should a status command have a flag to determine if everything should be fetched beforehand?

### command output:

:+1: for color.

### Formatting:

I was just going to go with yaml formatting in the general case. Is the real distinction on whether it r10k should output color/no color?

Also, thanks very much for submitting this awesome issue report! I really appreciate feedback like this!

**Comment by adrienthebo** [comment]
Support for module expected/actual versions added in  bd7ea47:

```
ops (/home/adrien/development/r10k/testing/deploy/ops/environments)
    - add_mysql_error_logs
        modules:
            - git
                actual: 13b2b8f0e93f3304f4b13c546246da7b51e78173
                expected: 13b2b8f0e93f3304f4b13c546246da7b51e78173
                type: git
            - hubot
                actual: 1ab6921e70ee1656ca753ea8c5f9591e8472eedb
                expected: 1ab6921e70ee1656ca753ea8c5f9591e8472eedb
                type: git
```

It doesn't encompass all of the behavior asked for in this ticket but it gets us a lot closer. I'm going to ship 1.4.0 with this behavior so that something can get out of the door; if additional functionality is required then we can incrementally revisit this and extend behavior in future releases.
