### ISSUE TITLE
issue non-existent in that revision

### ISSUE THREAD

**Issue by supriyawishesu** [puppetlabs/r10k#427]
Hi,

I am having an issue when i tried to deploy environment.
 This is my r10k.yaml file

```
cachedir: '/var/cache/r10k'

sources:
  mysource:
    type:  svn
    remote: 'http://xxx.xxx.xxx/svn/puppet/puppetlabs/puppet/environments/r10k-site'
    basedir: '/etc/puppetlabs/puppet/environments'
    username: 'xxxx'
    password: 'xxxx'
```

when i am deploying environment

```
/opt/puppet/bin/r10k deploy environment
ERROR    -> Command exited with non-zero exit code:
Command: svn --non-interactive ls http://xxx.xx.x.x/svn/puppet/puppetlabs/puppet/environments/r10k-site/branches --username xxxx --password xxxx
Stderr:
svn: URL 'http://xxxx.xxx.xxx/svn/puppet/puppetlabs/puppet/environments/r10k-site/branches' non-existent in that revision
Exit code: 1
```
