### ISSUE TITLE
Environment collision at /etc/puppetlabs/puppet/environments/production between development:production and testing:production

### ISSUE THREAD

**Issue by supriyawishesu** [puppetlabs/r10k#429]
Hi,

I am having an issue when using r10k.yaml.

Here is my r10k.yaml

```
cachedir: '/var/cache/r10k'

sources:
  testing:
    type:  svn
    remote: 'http://xxx.xxx.xxxx/svn/puppet/puppetlabs/puppet/environments'
    basedir: '/etc/puppetlabs/puppet/environments'
    username: 'xxxx'
    password: 'xxxx'

  development:
    type:  svn
    remote: 'http://xxxxx.xxxx.xxx/svn/puppet/puppetlabs/puppet/environments'
    basedir: '/etc/puppetlabs/puppet/environments'
    username: 'xxxx'
    password: 'xxxx'
```

In My svn repositry i have branches too.

Here is the list:

```
 ls http://xxxx.xxx.xxxx/svn/puppet/puppetlabs/puppet/environments/branches:
development_branches
testing_branches
```

But it is stiill throwing me error

ERROR    -> Environment collision at /etc/puppetlabs/puppet/environments/production between development:production and testing:production
