### ISSUE TITLE
Allow some form of variable setting in r10k.yaml for interpolation in the Puppetfile

### ISSUE THREAD

**Issue by jharlow1** [puppetlabs/r10k#543]
We have a situation where our internal git repos are replicated out from dev to our production datacenter(s), so the dev/qa puppet masters access via something like:

git@devgit.ourdevdomain.com:awesome/puppet_module.git

But, in production, the masters need to hit:

git@prodgit.ourproddomain.com:awesome/puppet_module.git

We definitely don't want to maintain a completely separate Puppetfile, so the only option I can think of at the moment is some sort of DNS trickery, which I'd rather avoid.

It would be nice if we could do something in r10k.yaml like:

```
sources:
  ops:
    remote: 'git@prodgit.ourproddomain.com:awesome/control_repo.git'
    basedir: '/etc/puppetlabs/puppet/environments'
    vars:
      gitserver: 'git@prodgit.ourproddomain.com'
```

And then in Puppetfile, do something along the lines of:

```
mod 'puppet_module',
  :git => "#{vars['gitserver']}:awesome/puppet_module.git"
```

etc.

That way we could configure vars['gitserver'] differently on our Puppet masters depending on which one they have access to and keep the same Puppetfile across all our environments.

Figured making the variable a generic hash is probably best since people may have multiple sources or other uses for this functionality.

Thoughts?
