### ISSUE TITLE
Need proxy settings to apply to forge and github modules

### ISSUE THREAD

**Issue by benhocker** [puppetlabs/r10k#576]
I'm getting timeouts when using proxy when going to github instead of forge.

```
[root@server ~]# cat /etc/puppetlabs/r10k/r10k.yaml

---
cachedir: /opt/puppetlabs/server/data/puppetserver/r10k
sources:
  puppet:
    basedir: /etc/puppetlabs/code/environments
    remote: git@gitserver:org/config-mgmt.git
forge:
    proxy: http://proxy.company.com:80
git:
    private_key: /etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa
    provider: rugged
deploy:
    write_lock: Direct invocation of r10k is disabled when Code Manager is auto configured.
```

Here is short version of Puppetfile:

```
[root@server ~]# cat ~/config-mgmt/Puppetfile
forge "https://forge.puppetlabs.com"

mod "abstractit/sudo", "1.2.1" # Works
mod "camptocamp/augeas", "1.4.2" # Works
mod "camptocamp/postfix", # Times out when going to 
  :git    => "https://github.com/camptocamp/puppet-postfix.git",
  :branch => "master"
```

strace output:

```
connect(7, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("192.30.252.129")}, 16) = -1 ETIMEDOUT (Connection timed out)
```

Puppet Server log:

```
[root@server ~]# tail -f /var/log/puppetlabs/puppetserver/puppetserver.log
INFO     -> Deploying module /etc/puppetlabs/code-staging/environments/newbranch/modules/postfix
ERROR    -> Failed to connect to github.com: Connection timed out
```
