### ISSUE TITLE
Multiple tenancy with external hieradata documentation error

### ISSUE THREAD

**Issue by trobert2** [puppetlabs/r10k#601]
Hello,

I tried running with this configuration as in the example for Multiple tenancy and I get "undefined method `gsub' for nil:NilClass"

https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#multiple-tenancy-with-external-hieradata
[r10k.txt](https://github.com/puppetlabs/r10k/files/291269/r10k.txt)

I suspect that "main" should not be there and you are trying to highlight the use of the prefix?
Is the documentation wrong?

Thank you

**Comment by scotje** [comment]
Can you add `-v debug` and `--trace` to your `r10k` invocation and post the results (or a link to a gist) here?

**Comment by brettswift** [comment]
You might have caught something here.  Does it work without the main section? I'm guessing it should - just from a quick eye-ball of the example.

**Comment by scotje** [comment]
Yeah, looking at that example again, I think the fact that "main" is there is a typo. Try it with:

``` yaml
  sources:
    app1_data:
      remote: 'git://git-server.site/my-org/app1-hieradata'
      basedir: '/etc/puppet/hieradata'
      prefix: "app1"
    app1_modules:
      remote: 'git://git-server.site/my-org/app1-puppet-modules'
      basedir: '/etc/puppet/environments'
      prefix: "app1"
```
