### ISSUE TITLE
Should reset dirty working tree of a module when running `r10k deploy module foo`

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/r10k#61]
As discussed in IRC, consider the following scenario. R10k manages modules in `/etc/puppet/environments/$environment/modules`, in our case via a Puppetfile. Someone unwisely edits `/etc/puppet/environments/production/modules/foo/manifests/init.pp` directly on the Puppetmaster server (but doesn't commit the changes), so the local working tree of that module is now dirty.

I believe running `r10k deploy environment && r10k deploy module foo` should reset that dirty working tree, just like it would reset the module's branch if it were not in sync with the remote branch.

**Comment by antaflos** [comment]
I think the same should go for other r10k/Git-managed directories such as `/etc/puppet/environments/production/manifests` and files such as `/etc/puppet/environments/production/Puppetfile`.

Our `r10k.yaml` looks like this, for reference:

``` yaml
# A list of git repositories to create
:sources:
  :puppetmaster:
    remote: 'ssh://git@git.example.com:22/puppetmaster'
    basedir: '/etc/puppet/environments'
```

The `puppetmaster` repo contains, among other things, `manifests` and `hieradata`.

Local changes made to either `manifests` or `hieradata` should be reset/reverted when running `r10k deploy environment`.
